dependencies:
- name: activiti-rb-connector
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: common
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 1.1.2
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.92
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.92
