expose:
  Args: 
    - --v
    - 4
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

cleanup:
  Args: 
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

# Activiti Cloud DevOps Environment configuration settings.
global:
  gateway:
    ## Set to configure single domain name for all services using Go template 
    host: "activiti-cloud-gateway.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"

    ## Set enable TLS configuration on all exposed service ingresses
    http: true

    ## Set to configure gateway domain template using Jx environment expose.config.domain value
    domain: "CHANGEME"

    ## Configure global annotations for all service ingresses, i.e. 
    annotations: 
      certmanager.k8s.io/issuer: letsencrypt-prod
