expose:
  Args: 
    - --v
    - 4
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

cleanup:
  Args: 
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

# Annotate Jx GitOps environment expose controller config with &domain and &http anchors to link with Activiti global.gateway values
expose: 
  config:
    domain: &domain "nip.io"
    http: &http false
    tlsacme: true

global:
  gateway:
    ## Set to configure single domain name for all services, 
    # i.e. "activiti-cloud-gateway.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    host: "activiti-cloud-gateway.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"

    ## Set enable TLS configuration on all exposed service ingresses
    http: *http

    ## Set to configure gateway domain template, i.e. {{ .Release.Namespace }}.1.3.4.5.nip.io
    #  helm upgrade activiti . --install --set global.gateway.domain=1.2.3.4.nip.io
    domain: *domain

    ## Configure global annotations for all service ingresses, i.e. 
    annotations: 
      certmanager.k8s.io/issuer: letsencrypt-prod
  ## Keycloak configuration
  keycloak:
    ## Configure Activiti Keycloak host template, i.e. "activiti-keycloak.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    # if not set, Keycloak Ingress will use gateway host domain, i.e. http(s)://{{ template \"common.gateway-host\" . }}/auth
    host: ""

    ## Set full url to configure external Keycloak, https://my.keycloak.com/auth
    # if set, Activiti will use external Keycloak deployment configuration 
    url: ""

    ## Configure Keycloak realm
    realm: "activiti"
    resource: "activiti"
    client: "activiti"
